name: langsync
description: an AI powered localization tool for any platform and language.
version: 1.0.0
homepage: https://langsync.app
repository: https://github.com/LangSync/cli

environment:
  sdk: ">=2.19.0 <4.0.0"

dependencies:
  args: ^2.3.1
  cli_completion: ^0.4.0
  equatable: ^2.0.5
  hive: ^2.2.3
  http: ^1.1.0
  mason_logger: ^0.2.4
  meta: ^1.11.0
  path: ^1.8.3
  yaml: ^3.1.2

dev_dependencies:
  build_runner: ^2.0.0
  build_verify: ^3.0.0
  build_version: ^2.0.0
  mocktail: ">=0.3.0 <2.0.0"
  test: ^1.19.2
  very_good_analysis: ^4.0.0

executables:
  langsync:
